def get_treatments():
    return {
        'Apple___Apple_scab': "Apply a fungicide like Captan or Mancozeb. Ensure proper pruning and sanitation.",
        'Apple___Black_rot': "Remove infected plant parts and apply fungicides like Captan or Topsin-M.",
        'Apple___Cedar_apple_rust': "Use fungicides such as Myclobutanil and avoid planting near cedar trees.",
        'Apple___healthy': "No treatment needed. Keep monitoring for any signs of disease.",
        'Blueberry___healthy': "No treatment needed. Maintain good care and monitoring.",
        'Cherry_(including_sour)___Powdery_mildew': "Apply sulfur-based fungicides or potassium bicarbonate.",
        'Cherry_(including_sour)___healthy': "No treatment needed. Maintain regular care.",
        'Corn_(maize)___Cercospora_leaf_spot_Gray_leaf_spot': "Use fungicides such as strobilurins and manage crop residue.",
        'Corn_(maize)___Common_rust_': "Apply fungicides like Mancozeb or Propiconazole and rotate crops.",
        'Corn_(maize)___Northern_Leaf_Blight': "Use resistant hybrids and apply fungicides like Triazoles if necessary.",
        'Corn_(maize)___healthy': "No treatment needed. Keep monitoring.",
        'Grape___Black_rot': "Apply fungicides like Mancozeb and practice proper pruning.",
        'Grape___Esca_(Black_Measles)': "Prune out infected canes and apply fungicides if necessary.",
        'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)': "Apply fungicides such as Captan and ensure proper vineyard sanitation.",
        'Grape___healthy': "No treatment needed. Maintain good care.",
        'Orange___Haunglongbing_(Citrus_greening)': "Unfortunately, no effective treatment. Focus on managing the disease by removing infected trees and controlling psyllid populations.",
        'Peach___Bacterial_spot': "Apply copper-based bactericides and practice good orchard sanitation.",
        'Peach___healthy': "No treatment needed. Keep monitoring.",
        'Pepper,_bell___Bacterial_spot': "Use copper-based fungicides and ensure proper irrigation practices.",
        'Pepper,_bell___healthy': "No treatment needed. Maintain regular care.",
        'Potato___Early_blight': "Apply fungicides like Chlorothalonil and practice crop rotation.",
        'Potato___Late_blight': "Use fungicides such as Mancozeb or Metalaxyl and remove infected plants.",
        'Potato___healthy': "No treatment needed. Keep monitoring.",
        'Raspberry___healthy': "No treatment needed. Maintain good care.",
        'Soybean___healthy': "No treatment needed. Maintain regular care.",
        'Squash___Powdery_mildew': "Apply sulfur-based fungicides and ensure good air circulation.",
        'Strawberry___Leaf_scorch': "Use fungicides such as Captan and remove infected leaves.",
        'Strawberry___healthy': "No treatment needed. Keep monitoring.",
        'Tomato___Bacterial_spot': "Apply copper-based fungicides and avoid overhead watering.",
        'Tomato___Early_blight': "Use fungicides like Mancozeb or Chlorothalonil and practice crop rotation.",
        'Tomato___Late_blight': "Apply fungicides such as Copper-based compounds and remove affected plants.",
        'Tomato___Leaf_Mold': "Use fungicides like Chlorothalonil and ensure proper ventilation.",
        'Tomato___Septoria_leaf_spot': "Apply fungicides such as Mancozeb and remove affected leaves.",
        'Tomato___Spider_mites Two-spotted_spider_mite': "Use miticides and introduce natural predators like ladybugs.",
        'Tomato___Target_Spot': "Apply fungicides like Difenoconazole and practice crop rotation.",
        'Tomato___Tomato_Yellow_Leaf_Curl_Virus': "Unfortunately, no effective chemical treatment. Focus on controlling whiteflies and use resistant varieties.",
        'Tomato___Tomato_mosaic_virus': "No chemical treatment available. Practice good sanitation and use resistant varieties.",
        'Tomato___healthy': "No treatment needed. Keep monitoring."
    }
